vueAddress = "http://test.renjiwulian.com/"

[mysql]
    DBDriver = "mysql"
    DBName ="BCI"
    UserName ="root"
    Password ="Daiguojun123456"
    Charset="utf8mb4"

[wechat]
    AppID = "wx2203c68c9311ea43"
    AppSecret = "40c40547e174ed99d1281b2890f7eeb3"
    OriID = "gh_b4421d95f839"
    Token = "HMIIoT"
    EncodedAESKey = "iesxoHBsnaKVry5E8xd8gavmJLTVVNcd8aS7w3KYOaU"

[app]
    port=80




