[hotreload]
  suffixes = [".go"]
  ignore = []

[app]
    # app名称
    name = "BCI"
    # app url
    url = ""
    # app文档地址
    doc = "./apidoc"
    addr = ":80"
    #单元测试调试信息
    debug = false

[server]
    serverAddress = "http://test.renjiwulian.com"
    
[wechat]
    AppId = ""
    AppSecret = ""
    OriId = ""
    Token = ""
    EncodedAESKey = ""

#数据库驱动
[database]
    driver = "mysql"

[mysql]
   databaseName ="BCI"
   databaseUserName ="root"
   databasePassword ="Daiguojun123456"

[mongodb]
    connect = "mongodb://root:123456@127.0.0.1:27017/admin"

[sqlite]
    connect = "/tmp/gorm.db"

[redis]
    Addr = "localhost:6379"
    Password = ""
    DB = 0

[test]
    #测试登录用户名
    LoginUserName = "panta"
    #测试用户名
    LoginName = "pantaZheng"
    #测试用户名
    LoginPwd = "test_user_pwd"
    #测试数据库驱动
    DataBaseDriver = "sqlite3"
    #测试数据库
    DataBaseConnect = "/cache/gorm.db"


