[hotreload]
  suffixes = [".go"]
  ignore = []

[wechat]
    AppId = "wx2203c68c9311ea43"
    AppSecret = "40c40547e174ed99d1281b2890f7eeb3"
    OriId = "gh_b4421d95f839"
    Token = "HMIIoT"
    EncodedAESKey = "iesxoHBsnaKVry5E8xd8gavmJLTVVNcd8aS7w3KYOaU"

#数据库驱动
[database]
    dirver = "mysql"

[mysql]
   databaseName ="BCI"
   databaseUserName ="root"
   databasePassword ="Daiguojun123456"

